name: Upload update
on:
  push:
    branches:
      - stable
      - beta

jobs:
  name: Upload
  runs-on: ubuntu-latest
  steps:
    - name: Clone stable
      uses: actions/checkout@v2
      with:
        path: stable
        branch: stable
    - name: Clone beta
      uses: actions/checkout@v2
      with:
        path: beta
        branch: beta
    - name: Clone master
      uses: actions/checkout@v2
      with:
        path: master
        branch: master
    - name: Copy files
      run: |
        rm -r master/*
        cp -r stable/* master/
        cp -r beta/* master/
    - name: Check for changes
      run: |
        cd master
        git status | grep -q "nothing to commit, working tree clean" \
        || echo "::set-env name=HAS_CHANGES::1"
    - name: Setting up credentials
      if: ${{ env.HAS_CHANGES }}
      run: |
        cd target
        git config user.email ${{ secrets.COMMITER_EMAIL }}
        git config user.name ${{ secrets.COMMITER_NAME }}
    - name: Commit changes
      if: ${{ env.HAS_CHANGES }}
      run: |
        cd target
        git add -A
        git commit -m "${{ github.event.head_commit.message }}"
    - name: Push changes to target
      if: ${{ env.HAS_CHANGES }}
      run: |
        cd target
        git push "https://${{ secrets.KOTATO_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
